ALTER TABLE messages
    MODIFY COLUMN message_type ENUM('TEXT', 'IMAGE', 'FILE', 'SYSTEM', 'PROJECT_CARD') NOT NULL DEFAULT 'TEXT',
    ADD COLUMN file_url VARCHAR(2048) NULL,
    ADD COLUMN file_name VARCHAR(255) NULL,
    ADD COLUMN file_size BIGINT NULL,
    ADD COLUMN content_type VARCHAR(100) NULL;
