ALTER TABLE projects
    MODIFY COLUMN status ENUM('WAITING', 'WORKING', 'COMPLETION_PENDING', 'COMPLETED', 'REJECTED', 'CANCELED') NOT NULL DEFAULT 'WAITING';

ALTER TABLE projects
    ADD COLUMN completion_requested_by CHAR(36) NULL;
