spring:
  profiles:
    active: dev,local

  flyway:
    out-of-order: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.flywaydb: debug

server:
  port: 8080

cloudflare:
  r2:
    account-id: ${CLOUDFLARE_R2_ACCOUNT_ID}
    access-key-id: ${CLOUDFLARE_R2_ACCESS_KEY_ID}
    secret-access-key: ${CLOUDFLARE_R2_SECRET_ACCESS_KEY}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
    public-url: ${CLOUDFLARE_R2_PUBLIC_URL}