spring:
  profiles:
    active: dev,local

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  flyway:
    out-of-order: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.flywaydb: debug

server:
  port: 8080
